package commands

// Code generated by glean from glean.go:5. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"time"

	"exchange"
)

const cols = " `id`, `type`, `order_id` "
const selectPrefix = "select " + cols + " from commands where "

var _ time.Time

func Lookup(ctx context.Context, dbc dbc, id int64) (*exchange.Command, error) {
	return lookupWhere(ctx, dbc, "id=?", id)
}

// lookupWhere queries the commands table with the provided where clause, then scans
// and returns a single row.
func lookupWhere(ctx context.Context, dbc dbc, where string, args ...interface{}) (*exchange.Command, error) {
	return scan(dbc.QueryRowContext(ctx, selectPrefix+where, args...))
}

// scanWhere queries the commands table with the provided where clause and
// calls callback with the results one row at a time.
//
// An intermediate buffered channel is introduced between the internal callback
// and the provided callback. This allows testing (with only a single DB connection)
// if the number of rows fits in the buffer (< 100).
func scanWhere(in context.Context, dbc *sql.DB, fn func(*exchange.Command) error,
	where string, args ...interface{}) error {

	// If the reader errors, we need to cancel the streamer.
	ctx, cancel := context.WithCancel(in)
	defer func() {
		// Testing work around: allow scanWhere to return before we cancel the context.
		// See src/bitx/db/db_test.go:TestCtxCancelIssue.
		time.Sleep(time.Millisecond)
		cancel()
	}()

	// Note: tests will block if scanning more than 100 rows.
	ch := make(chan *exchange.Command, 100)

	fn2 := func(i *exchange.Command) error {
		ch <- i
		return nil
	}

	// Start streamer, from DB into the channel.
	var scanErr error
	go func() {
		// When the streamer is done, close the channel for the reader to return.
		defer close(ch)
		scanErr = innerScanWhere(ctx, dbc, fn2, where, args...)
	}()

	// Start reader, from the channel until closed or error.
	for i := range ch {
		if err := fn(i); err != nil {
			return err
		}
	}

	return scanErr
}

func innerScanWhere(ctx context.Context, dbc dbc, f func(*exchange.Command) error,
	where string, args ...interface{}) error {

	rows, err := dbc.QueryContext(ctx, selectPrefix+where, args...)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		r, err := scan(rows)
		if err != nil {
			return err
		}
		err = f(r)
		if err != nil {
			return err
		}
	}
	return rows.Err()
}

// listWhere queries the commands table with the provided where clause, then scans
// and returns all the rows.
func listWhere(ctx context.Context, dbc dbc, where string, args ...interface{}) ([]exchange.Command, error) {

	rows, err := dbc.QueryContext(ctx, selectPrefix+where, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var res []exchange.Command
	for rows.Next() {
		r, err := scan(rows)
		if err != nil {
			return nil, err
		}
		res = append(res, *r)
	}

	return res, rows.Err()
}

func scan(row row) (*exchange.Command, error) {
	var g glean

	err := row.Scan(&g.ID, &g.Type, &g.OrderId)
	if err != nil {
		return nil, err
	}

	return &exchange.Command{
		ID:      g.ID,
		Type:    g.Type,
		OrderId: g.OrderId,
	}, nil
}

// dbc is a common interface for *sql.DB and *sql.Tx.
type dbc interface {
	QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// row is a common interface for *sql.Rows and *sql.Row.
type row interface {
	Scan(dest ...interface{}) error
}
